version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    restart: always
    environment:
      ENV: DEVELOPMENT
      DB_USERNAME: erik
      DB_PASSWORD: 123456
      DB_DATABASE: emochat
      DB_HOST: db
    depends_on:
      - db
    links:
      - db:db
      - smtp:smtp
      - cache:cache

  db:
      image: mysql/mysql-server:5.7
      restart: always
      volumes:
        - ./db:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: emochat
          MYSQL_USER: erik
          MYSQL_PASSWORD: 123456
      ports:
        - 3306:3306

  smtp:
      image: djfarrelly/maildev:latest
      ports:
        - 25:25
        - 8080:80

  cache:
      image: memcached
      ports:
        - "11211:11211"
